Testing
bakaphp/hengen pull request #1
Opened 2021-08-12 20:16 UTC by FredPeal

start with testing for package

2021-08-12 22:19 UTC, kaioken requested changes

2021-08-12 22:19 UTC, kaioken commented on src/Transformers/ADF.php
> +
@FredPeal extra space?

2021-08-12 22:20 UTC, kaioken requested changes

2021-08-12 22:20 UTC, kaioken commented on tests/unit/AdfTransformerTest.php
> +        $adfTransformer = new ADF($leads, ['template' => 'dealer-content']);
@FredPeal add a test with multiple models

2021-08-17 13:26 UTC, kaioken requested changes

2021-08-17 13:26 UTC, kaioken commented on src/Communicators/ADF.php
> +        $mail->to($this->company->user->getEmail())
@FredPeal should it be sendnow ?

2021-08-17 13:26 UTC, kaioken commented on src/Hengen.php
> +    public static function getTransformer(string $type, LeadsInterfaces $leads, array $options = [], Model ...$args)
@FredPeal overall all function documentation

2021-08-17 13:26 UTC, kaioken commented on src/Transformers/ADF.php
> +    protected Model $lead;
@FredPeal shoulnt this be a lead interface or a model interface?

2021-08-17 14:53 UTC, rwhite27 approved these changes

2021-08-17 21:33 UTC, merged